const SliderData = [
  {
    id: 8,
    placement: "home",
    type: "slideshow",
    banner: "banners/Banner_web_ReactJS.png",
    title: "Học ReactJS Miễn Phí!",
    description:
      "Khóa học ReactJS từ cơ bản tới nâng cao. Kết quả của khóa học này là bạn có thể làm hầu hết các dự án thường gặp với ReactJS.",
    alt: "Khoá học ReactJS online tại F8",
    cta_title: "Đăng ký ngay",
    link_to: "https://fullstack.edu.vn/courses/reactjs?ref=banner",
    data: {
      props: {
        style: {
          "--cta-hover-color": "#2877FA",
          background: "linear-gradient(to right, #2877FA, #6717CD",
        },
      },
    },
    is_blank: 1,
    priority: 0,
    expired: "2022-12-12 00:00:00",
    created_at: "2022-12-11T10:00:00.000000Z",
    updated_at: "2022-12-11T10:00:00.000000Z",
    banner_url:
      "https://files.fullstack.edu.vn/f8-prod/banners/Banner_web_ReactJS.png",
  },
  {
    id: 3,
    placement: "home",
    type: "slideshow",
    banner: "banners/Banner_01_2.png",
    title: "Thành Quả của Học Viên",
    description:
      "Để đạt được kết quả tốt trong mọi việc ta cần xác định mục tiêu rõ ràng cho việc đó. Học lập trình cũng không là ngoại lệ.",
    alt: "Thành quả của học viên",
    cta_title: "Xem thành quả",
    link_to:
      "https://fullstack.edu.vn/blog/tong-hop-cac-san-pham-cua-hoc-vien-tai-f8.html",
    data: {
      props: {
        style: {
          "--cta-hover-color": "#7612ff",
          background: "linear-gradient(to right, #7612ff, #05b2ff)",
        },
      },
    },
    is_blank: 1,
    priority: 10,
    expired: "2022-12-12 00:00:00",
    created_at: "2022-12-11T10:00:00.000000Z",
    updated_at: "2022-12-11T10:00:00.000000Z",
    banner_url:
      "https://files.fullstack.edu.vn/f8-prod/banners/Banner_01_2.png",
  },
  {
    id: 4,
    placement: "home",
    type: "slideshow",
    banner: "banners/Banner_03_youtube.png",
    title: "F8 trên Youtube",
    description:
      "F8 được nhắc tới ở mọi nơi, ở đâu có cơ hội việc làm cho nghề IT và có những con người yêu thích lập trình F8 sẽ ở đó.",
    alt: "F8 trên Youtube",
    cta_title: "Truy cập kênh",
    link_to: "https://www.youtube.com/channel/UCNSCWwgW-rwmoE3Yc4WmJhw",
    data: {
      props: {
        style: {
          "--cta-hover-color": "#fe215e",
          background: "linear-gradient(to right, #fe215e , #ff9402",
        },
      },
    },
    is_blank: 1,
    priority: 11,
    expired: "2022-12-12 00:00:00",
    created_at: "2022-12-11T10:00:00.000000Z",
    updated_at: "2022-12-11T10:00:00.000000Z",
    banner_url:
      "https://files.fullstack.edu.vn/f8-prod/banners/Banner_03_youtube.png",
  },
  {
    id: 5,
    placement: "home",
    type: "slideshow",
    banner: "banners/Banner_04_2.png",
    title: "F8 trên Facebook",
    description:
      "F8 được nhắc tới ở mọi nơi, ở đâu có cơ hội việc làm cho nghề IT và có những con người yêu thích lập trình F8 sẽ ở đó.",
    alt: "F8 trên Facebook",
    cta_title: "Truy cập nhóm",
    link_to: "https://www.facebook.com/groups/649972919142215",
    data: {
      props: {
        style: {
          "--cta-hover-color": "#007efe",
          background: "linear-gradient(to right, #007efe, #06c3fe",
        },
      },
    },
    is_blank: 1,
    priority: 12,
    expired: "2022-12-12 00:00:00",
    created_at: "2022-12-11T10:00:00.000000Z",
    updated_at: "2022-12-11T10:00:00.000000Z",
    banner_url:
      "https://files.fullstack.edu.vn/f8-prod/banners/Banner_04_2.png",
  },
];
const CoursesData = {
  free_courses: [
    {
      id: 7,
      title: "Kiến Thức Nhập Môn IT",
      slug: "lessons-for-newbie",
      description:
        "Để có cái nhìn tổng quan về ngành IT - Lập trình web các bạn nên xem các videos tại khóa này trước nhé.",
      image: "courses/7.png",
      icon: "courses/7/6200b81f52d83.png",
      video_type: "youtube",
      video: "M62l1xA5Eu8",
      old_price: 0,
      price: 0,
      pre_order_price: 0,
      students_count: 73781,
      is_pro: false,
      is_selling: false,
      published_at: "2020-02-10T14:23:13.000000Z",
      is_registered: true,
      user_progress: 66,
      last_completed_at: "2022-01-24 14:49:26",
      image_url: "https://files.fullstack.edu.vn/f8-prod/courses/7.png",
      icon_url:
        "https://files.fullstack.edu.vn/f8-prod/courses/7/6200b81f52d83.png",
      video_url: "https://www.youtube.com/watch?v=M62l1xA5Eu8",
      is_coming_soon: false,
      is_pre_order: false,
      is_published: true,
    },
    {
      id: 13,
      title: "Xây Dựng Website với ReactJS",
      slug: "reactjs",
      description:
        "Khóa học ReactJS từ cơ bản tới nâng cao, kết quả của khóa học này là bạn có thể làm hầu hết các dự án thường gặp với ReactJS. Cuối khóa học này bạn sẽ sở hữu một dự án giống Tiktok.com, bạn có thể tự tin đi xin việc khi nắm chắc các kiến thức được chia sẻ trong khóa học này.",
      image: "courses/13/13.png",
      icon: "courses/13/6200af9262b30.png",
      video_type: "youtube",
      video: "x0fSBAgBrOQ",
      old_price: 0,
      price: 0,
      pre_order_price: 0,
      students_count: 56070,
      is_pro: false,
      is_selling: false,
      published_at: "2020-02-10T14:23:13.000000Z",
      is_registered: true,
      user_progress: 100,
      last_completed_at: "2022-03-26 15:37:30",
      image_url: "https://files.fullstack.edu.vn/f8-prod/courses/13/13.png",
      icon_url:
        "https://files.fullstack.edu.vn/f8-prod/courses/13/6200af9262b30.png",
      video_url: "https://www.youtube.com/watch?v=x0fSBAgBrOQ",
      is_coming_soon: false,
      is_pre_order: false,
      is_published: true,
    },
    {
      id: 2,
      title: "HTML, CSS từ Zero đến Hero",
      slug: "html-css",
      description:
        "Trong khóa này chúng ta sẽ cùng nhau xây dựng giao diện 2 trang web là The Band & Shopee.",
      image: "courses/2.png",
      icon: "courses/2/6200aecea81de.png",
      video_type: "youtube",
      video: "R6plN3FvzFY",
      old_price: 0,
      price: 0,
      pre_order_price: 0,
      students_count: 264399,
      is_pro: false,
      is_selling: false,
      published_at: "2020-02-10T14:23:13.000000Z",
      is_registered: true,
      user_progress: 99,
      last_completed_at: "2021-12-14 21:28:05",
      image_url: "https://files.fullstack.edu.vn/f8-prod/courses/2.png",
      icon_url:
        "https://files.fullstack.edu.vn/f8-prod/courses/2/6200aecea81de.png",
      video_url: "https://www.youtube.com/watch?v=R6plN3FvzFY",
      is_coming_soon: false,
      is_pre_order: false,
      is_published: true,
    },
    {
      id: 3,
      title: "Responsive Với Grid System",
      slug: "responsive-web-design",
      description:
        "Trong khóa này chúng ta sẽ học về cách xây dựng giao diện web responsive với Grid System, tương tự Bootstrap 4.",
      image: "courses/3.png",
      icon: "courses/3/6200afe1240bb.png",
      video_type: "youtube",
      video: "uz5LIP85J5Y",
      old_price: 0,
      price: 0,
      pre_order_price: 0,
      students_count: 32143,
      is_pro: false,
      is_selling: false,
      published_at: "2020-02-10T14:23:13.000000Z",
      is_registered: true,
      user_progress: 100,
      last_completed_at: "2021-12-26 08:47:58",
      image_url: "https://files.fullstack.edu.vn/f8-prod/courses/3.png",
      icon_url:
        "https://files.fullstack.edu.vn/f8-prod/courses/3/6200afe1240bb.png",
      video_url: "https://www.youtube.com/watch?v=uz5LIP85J5Y",
      is_coming_soon: false,
      is_pre_order: false,
      is_published: true,
    },
    {
      id: 1,
      title: "Lập Trình JavaScript Cơ Bản",
      slug: "javascript-co-ban",
      description:
        "Học Javascript cơ bản phù hợp cho người chưa từng học lập trình. Với hơn 100 bài học và có bài tập thực hành sau mỗi bài học.",
      image: "courses/1.png",
      icon: "courses/1/6200ad9d8a2d8.png",
      video_type: "youtube",
      video: "0SJE9dYdpps",
      old_price: 0,
      price: 0,
      pre_order_price: 0,
      students_count: 169605,
      is_pro: false,
      is_selling: false,
      published_at: "2020-02-10T14:23:13.000000Z",
      is_registered: true,
      user_progress: 87,
      last_completed_at: "2022-03-12 03:31:08",
      image_url: "https://files.fullstack.edu.vn/f8-prod/courses/1.png",
      icon_url:
        "https://files.fullstack.edu.vn/f8-prod/courses/1/6200ad9d8a2d8.png",
      video_url: "https://www.youtube.com/watch?v=0SJE9dYdpps",
      is_coming_soon: false,
      is_pre_order: false,
      is_published: true,
    },
    {
      id: 12,
      title: "Lập Trình JavaScript Nâng Cao",
      slug: "javascript-nang-cao",
      description:
        "Hiểu sâu hơn về cách Javascript hoạt động, tìm hiểu về IIFE, closure, reference types, this keyword, bind, call, apply, prototype, ...",
      image: "courses/12.png",
      icon: "courses/12/6200af2620118.png",
      video_type: "youtube",
      video: "MGhw6XliFgo",
      old_price: 0,
      price: 0,
      pre_order_price: 0,
      students_count: 22726,
      is_pro: false,
      is_selling: false,
      published_at: "2020-02-10T14:23:13.000000Z",
      is_registered: true,
      user_progress: 100,
      last_completed_at: "2022-03-10 14:33:49",
      image_url: "https://files.fullstack.edu.vn/f8-prod/courses/12.png",
      icon_url:
        "https://files.fullstack.edu.vn/f8-prod/courses/12/6200af2620118.png",
      video_url: "https://www.youtube.com/watch?v=MGhw6XliFgo",
      is_coming_soon: false,
      is_pre_order: false,
      is_published: true,
    },
    {
      id: 6,
      title: "Node & ExpressJS",
      slug: "nodejs",
      description:
        "Học Back-end với Node & ExpressJS framework, hiểu các khái niệm khi làm Back-end và xây dựng RESTful API cho trang web.",
      image: "courses/6.png",
      icon: "courses/6/6200afb926038.png",
      video_type: "youtube",
      video: "z2f7RHgvddc",
      old_price: 0,
      price: 0,
      pre_order_price: 0,
      students_count: 27489,
      is_pro: false,
      is_selling: false,
      published_at: "2020-02-10T14:23:13.000000Z",
      is_registered: true,
      user_progress: 11,
      last_completed_at: "2022-01-08 22:24:04",
      image_url: "https://files.fullstack.edu.vn/f8-prod/courses/6.png",
      icon_url:
        "https://files.fullstack.edu.vn/f8-prod/courses/6/6200afb926038.png",
      video_url: "https://www.youtube.com/watch?v=z2f7RHgvddc",
      is_coming_soon: false,
      is_pre_order: false,
      is_published: true,
    },
    {
      id: 4,
      title: 'App "Đừng Chạm Tay Lên Mặt"',
      slug: "tool-canh-bao-so-len-mat",
      description:
        "Xây dựng ứng dụng đưa ra cảnh báo khi người dùng sờ tay lên mặt. Chúng ta sẽ sử dụng thư viện ReactJS & Tensoflow để hoàn thiện ứng dụng này.",
      image: "courses/4/61a9e9e701506.png",
      icon: null,
      video_type: "youtube",
      video: "r6GWbQL-qwA",
      old_price: 0,
      price: 0,
      pre_order_price: 0,
      students_count: 4364,
      is_pro: false,
      is_selling: false,
      published_at: "2020-02-10T14:23:13.000000Z",
      is_registered: false,
      user_progress: 0,
      last_completed_at: null,
      image_url:
        "https://files.fullstack.edu.vn/f8-prod/courses/4/61a9e9e701506.png",
      icon_url: "",
      video_url: "https://www.youtube.com/watch?v=r6GWbQL-qwA",
      is_coming_soon: false,
      is_pre_order: false,
      is_published: true,
    },
  ],
  learning_paths: [
    {
      id: 2,
      title: "Lộ trình học Front-end",
      slug: "front-end-development",
      image: "learning-paths/2/61a0439062b82.png",
      courses: [
        {
          id: 7,
          title: "Kiến Thức Nhập Môn IT",
          slug: "lessons-for-newbie",
          description:
            "Để có cái nhìn tổng quan về ngành IT - Lập trình web các bạn nên xem các videos tại khóa này trước nhé.",
          image: "courses/7.png",
          icon: "courses/7/6200b81f52d83.png",
          video_type: "youtube",
          video: "M62l1xA5Eu8",
          old_price: 0,
          price: 0,
          pre_order_price: 0,
          students_count: 73781,
          is_pro: false,
          is_selling: false,
          published_at: "2020-02-10T14:23:13.000000Z",
          is_registered: true,
          user_progress: 66,
          last_completed_at: "2022-01-24 14:49:26",
          image_url: "https://files.fullstack.edu.vn/f8-prod/courses/7.png",
          icon_url:
            "https://files.fullstack.edu.vn/f8-prod/courses/7/6200b81f52d83.png",
          video_url: "https://www.youtube.com/watch?v=M62l1xA5Eu8",
          is_coming_soon: false,
          is_pre_order: false,
          is_published: true,
          related_courses: [],
        },
        {
          id: 2,
          title: "HTML, CSS từ Zero đến Hero",
          slug: "html-css",
          description:
            "Trong khóa này chúng ta sẽ cùng nhau xây dựng giao diện 2 trang web là The Band & Shopee.",
          image: "courses/2.png",
          icon: "courses/2/6200aecea81de.png",
          video_type: "youtube",
          video: "R6plN3FvzFY",
          old_price: 0,
          price: 0,
          pre_order_price: 0,
          students_count: 264399,
          is_pro: false,
          is_selling: false,
          published_at: "2020-02-10T14:23:13.000000Z",
          is_registered: true,
          user_progress: 99,
          last_completed_at: "2021-12-14 21:28:05",
          image_url: "https://files.fullstack.edu.vn/f8-prod/courses/2.png",
          icon_url:
            "https://files.fullstack.edu.vn/f8-prod/courses/2/6200aecea81de.png",
          video_url: "https://www.youtube.com/watch?v=R6plN3FvzFY",
          is_coming_soon: false,
          is_pre_order: false,
          is_published: true,
          related_courses: [],
        },
        {
          id: 3,
          title: "Responsive Với Grid System",
          slug: "responsive-web-design",
          description:
            "Trong khóa này chúng ta sẽ học về cách xây dựng giao diện web responsive với Grid System, tương tự Bootstrap 4.",
          image: "courses/3.png",
          icon: "courses/3/6200afe1240bb.png",
          video_type: "youtube",
          video: "uz5LIP85J5Y",
          old_price: 0,
          price: 0,
          pre_order_price: 0,
          students_count: 32143,
          is_pro: false,
          is_selling: false,
          published_at: "2020-02-10T14:23:13.000000Z",
          is_registered: true,
          user_progress: 100,
          last_completed_at: "2021-12-26 08:47:58",
          image_url: "https://files.fullstack.edu.vn/f8-prod/courses/3.png",
          icon_url:
            "https://files.fullstack.edu.vn/f8-prod/courses/3/6200afe1240bb.png",
          video_url: "https://www.youtube.com/watch?v=uz5LIP85J5Y",
          is_coming_soon: false,
          is_pre_order: false,
          is_published: true,
          related_courses: [],
        },
        {
          id: 1,
          title: "Lập Trình JavaScript Cơ Bản",
          slug: "javascript-co-ban",
          description:
            "Học Javascript cơ bản phù hợp cho người chưa từng học lập trình. Với hơn 100 bài học và có bài tập thực hành sau mỗi bài học.",
          image: "courses/1.png",
          icon: "courses/1/6200ad9d8a2d8.png",
          video_type: "youtube",
          video: "0SJE9dYdpps",
          old_price: 0,
          price: 0,
          pre_order_price: 0,
          students_count: 169605,
          is_pro: false,
          is_selling: false,
          published_at: "2020-02-10T14:23:13.000000Z",
          is_registered: true,
          user_progress: 87,
          last_completed_at: "2022-03-12 03:31:08",
          image_url: "https://files.fullstack.edu.vn/f8-prod/courses/1.png",
          icon_url:
            "https://files.fullstack.edu.vn/f8-prod/courses/1/6200ad9d8a2d8.png",
          video_url: "https://www.youtube.com/watch?v=0SJE9dYdpps",
          is_coming_soon: false,
          is_pre_order: false,
          is_published: true,
          related_courses: [],
        },
        {
          id: 12,
          title: "Lập Trình JavaScript Nâng Cao",
          slug: "javascript-nang-cao",
          description:
            "Hiểu sâu hơn về cách Javascript hoạt động, tìm hiểu về IIFE, closure, reference types, this keyword, bind, call, apply, prototype, ...",
          image: "courses/12.png",
          icon: "courses/12/6200af2620118.png",
          video_type: "youtube",
          video: "MGhw6XliFgo",
          old_price: 0,
          price: 0,
          pre_order_price: 0,
          students_count: 22726,
          is_pro: false,
          is_selling: false,
          published_at: "2020-02-10T14:23:13.000000Z",
          is_registered: true,
          user_progress: 100,
          last_completed_at: "2022-03-10 14:33:49",
          image_url: "https://files.fullstack.edu.vn/f8-prod/courses/12.png",
          icon_url:
            "https://files.fullstack.edu.vn/f8-prod/courses/12/6200af2620118.png",
          video_url: "https://www.youtube.com/watch?v=MGhw6XliFgo",
          is_coming_soon: false,
          is_pre_order: false,
          is_published: true,
          related_courses: [],
        },
        {
          id: 13,
          title: "Xây Dựng Website với ReactJS",
          slug: "reactjs",
          description:
            "Khóa học ReactJS từ cơ bản tới nâng cao, kết quả của khóa học này là bạn có thể làm hầu hết các dự án thường gặp với ReactJS. Cuối khóa học này bạn sẽ sở hữu một dự án giống Tiktok.com, bạn có thể tự tin đi xin việc khi nắm chắc các kiến thức được chia sẻ trong khóa học này.",
          image: "courses/13/13.png",
          icon: "courses/13/6200af9262b30.png",
          video_type: "youtube",
          video: "x0fSBAgBrOQ",
          old_price: 0,
          price: 0,
          pre_order_price: 0,
          students_count: 56070,
          is_pro: false,
          is_selling: false,
          published_at: "2020-02-10T14:23:13.000000Z",
          is_registered: true,
          user_progress: 100,
          last_completed_at: "2022-03-26 15:37:30",
          image_url: "https://files.fullstack.edu.vn/f8-prod/courses/13/13.png",
          icon_url:
            "https://files.fullstack.edu.vn/f8-prod/courses/13/6200af9262b30.png",
          video_url: "https://www.youtube.com/watch?v=x0fSBAgBrOQ",
          is_coming_soon: false,
          is_pre_order: false,
          is_published: true,
          related_courses: [],
        },
      ],
      image_url:
        "https://files.fullstack.edu.vn/f8-prod/learning-paths/2/61a0439062b82.png",
    },
    {
      id: 3,
      title: "Lộ trình học Back-end",
      slug: "back-end-development",
      image: "learning-paths/3/61a0439cc779b.png",
      courses: [
        {
          id: 7,
          title: "Kiến Thức Nhập Môn IT",
          slug: "lessons-for-newbie",
          description:
            "Để có cái nhìn tổng quan về ngành IT - Lập trình web các bạn nên xem các videos tại khóa này trước nhé.",
          image: "courses/7.png",
          icon: "courses/7/6200b81f52d83.png",
          video_type: "youtube",
          video: "M62l1xA5Eu8",
          old_price: 0,
          price: 0,
          pre_order_price: 0,
          students_count: 73781,
          is_pro: false,
          is_selling: false,
          published_at: "2020-02-10T14:23:13.000000Z",
          is_registered: true,
          user_progress: 66,
          last_completed_at: "2022-01-24 14:49:26",
          image_url: "https://files.fullstack.edu.vn/f8-prod/courses/7.png",
          icon_url:
            "https://files.fullstack.edu.vn/f8-prod/courses/7/6200b81f52d83.png",
          video_url: "https://www.youtube.com/watch?v=M62l1xA5Eu8",
          is_coming_soon: false,
          is_pre_order: false,
          is_published: true,
          related_courses: [],
        },
        {
          id: 2,
          title: "HTML, CSS từ Zero đến Hero",
          slug: "html-css",
          description:
            "Trong khóa này chúng ta sẽ cùng nhau xây dựng giao diện 2 trang web là The Band & Shopee.",
          image: "courses/2.png",
          icon: "courses/2/6200aecea81de.png",
          video_type: "youtube",
          video: "R6plN3FvzFY",
          old_price: 0,
          price: 0,
          pre_order_price: 0,
          students_count: 264399,
          is_pro: false,
          is_selling: false,
          published_at: "2020-02-10T14:23:13.000000Z",
          is_registered: true,
          user_progress: 99,
          last_completed_at: "2021-12-14 21:28:05",
          image_url: "https://files.fullstack.edu.vn/f8-prod/courses/2.png",
          icon_url:
            "https://files.fullstack.edu.vn/f8-prod/courses/2/6200aecea81de.png",
          video_url: "https://www.youtube.com/watch?v=R6plN3FvzFY",
          is_coming_soon: false,
          is_pre_order: false,
          is_published: true,
          related_courses: [],
        },
        {
          id: 1,
          title: "Lập Trình JavaScript Cơ Bản",
          slug: "javascript-co-ban",
          description:
            "Học Javascript cơ bản phù hợp cho người chưa từng học lập trình. Với hơn 100 bài học và có bài tập thực hành sau mỗi bài học.",
          image: "courses/1.png",
          icon: "courses/1/6200ad9d8a2d8.png",
          video_type: "youtube",
          video: "0SJE9dYdpps",
          old_price: 0,
          price: 0,
          pre_order_price: 0,
          students_count: 169605,
          is_pro: false,
          is_selling: false,
          published_at: "2020-02-10T14:23:13.000000Z",
          is_registered: true,
          user_progress: 87,
          last_completed_at: "2022-03-12 03:31:08",
          image_url: "https://files.fullstack.edu.vn/f8-prod/courses/1.png",
          icon_url:
            "https://files.fullstack.edu.vn/f8-prod/courses/1/6200ad9d8a2d8.png",
          video_url: "https://www.youtube.com/watch?v=0SJE9dYdpps",
          is_coming_soon: false,
          is_pre_order: false,
          is_published: true,
          related_courses: [],
        },
        {
          id: 12,
          title: "Lập Trình JavaScript Nâng Cao",
          slug: "javascript-nang-cao",
          description:
            "Hiểu sâu hơn về cách Javascript hoạt động, tìm hiểu về IIFE, closure, reference types, this keyword, bind, call, apply, prototype, ...",
          image: "courses/12.png",
          icon: "courses/12/6200af2620118.png",
          video_type: "youtube",
          video: "MGhw6XliFgo",
          old_price: 0,
          price: 0,
          pre_order_price: 0,
          students_count: 22726,
          is_pro: false,
          is_selling: false,
          published_at: "2020-02-10T14:23:13.000000Z",
          is_registered: true,
          user_progress: 100,
          last_completed_at: "2022-03-10 14:33:49",
          image_url: "https://files.fullstack.edu.vn/f8-prod/courses/12.png",
          icon_url:
            "https://files.fullstack.edu.vn/f8-prod/courses/12/6200af2620118.png",
          video_url: "https://www.youtube.com/watch?v=MGhw6XliFgo",
          is_coming_soon: false,
          is_pre_order: false,
          is_published: true,
          related_courses: [],
        },
        {
          id: 6,
          title: "Node & ExpressJS",
          slug: "nodejs",
          description:
            "Học Back-end với Node & ExpressJS framework, hiểu các khái niệm khi làm Back-end và xây dựng RESTful API cho trang web.",
          image: "courses/6.png",
          icon: "courses/6/6200afb926038.png",
          video_type: "youtube",
          video: "z2f7RHgvddc",
          old_price: 0,
          price: 0,
          pre_order_price: 0,
          students_count: 27489,
          is_pro: false,
          is_selling: false,
          published_at: "2020-02-10T14:23:13.000000Z",
          is_registered: true,
          user_progress: 11,
          last_completed_at: "2022-01-08 22:24:04",
          image_url: "https://files.fullstack.edu.vn/f8-prod/courses/6.png",
          icon_url:
            "https://files.fullstack.edu.vn/f8-prod/courses/6/6200afb926038.png",
          video_url: "https://www.youtube.com/watch?v=z2f7RHgvddc",
          is_coming_soon: false,
          is_pre_order: false,
          is_published: true,
          related_courses: [],
        },
      ],
      image_url:
        "https://files.fullstack.edu.vn/f8-prod/learning-paths/3/61a0439cc779b.png",
    },
  ],
  pro_courses: [],
  registered_courses: [
    {
      id: 13,
      title: "Xây Dựng Website với ReactJS",
      slug: "reactjs",
      description:
        "Khóa học ReactJS từ cơ bản tới nâng cao, kết quả của khóa học này là bạn có thể làm hầu hết các dự án thường gặp với ReactJS. Cuối khóa học này bạn sẽ sở hữu một dự án giống Tiktok.com, bạn có thể tự tin đi xin việc khi nắm chắc các kiến thức được chia sẻ trong khóa học này.",
      image: "courses/13/13.png",
      icon: "courses/13/6200af9262b30.png",
      video_type: "youtube",
      video: "x0fSBAgBrOQ",
      old_price: 0,
      price: 0,
      pre_order_price: 0,
      students_count: 56070,
      is_pro: false,
      is_selling: false,
      published_at: "2020-02-10T14:23:13.000000Z",
      is_registered: true,
      user_progress: 100,
      last_completed_at: "2022-03-26 15:37:30",
      image_url: "https://files.fullstack.edu.vn/f8-prod/courses/13/13.png",
      icon_url:
        "https://files.fullstack.edu.vn/f8-prod/courses/13/6200af9262b30.png",
      video_url: "https://www.youtube.com/watch?v=x0fSBAgBrOQ",
      is_coming_soon: false,
      is_pre_order: false,
      is_published: true,
    },
    {
      id: 1,
      title: "Lập Trình JavaScript Cơ Bản",
      slug: "javascript-co-ban",
      description:
        "Học Javascript cơ bản phù hợp cho người chưa từng học lập trình. Với hơn 100 bài học và có bài tập thực hành sau mỗi bài học.",
      image: "courses/1.png",
      icon: "courses/1/6200ad9d8a2d8.png",
      video_type: "youtube",
      video: "0SJE9dYdpps",
      old_price: 0,
      price: 0,
      pre_order_price: 0,
      students_count: 169605,
      is_pro: false,
      is_selling: false,
      published_at: "2020-02-10T14:23:13.000000Z",
      is_registered: true,
      user_progress: 87,
      last_completed_at: "2022-03-12 03:31:08",
      image_url: "https://files.fullstack.edu.vn/f8-prod/courses/1.png",
      icon_url:
        "https://files.fullstack.edu.vn/f8-prod/courses/1/6200ad9d8a2d8.png",
      video_url: "https://www.youtube.com/watch?v=0SJE9dYdpps",
      is_coming_soon: false,
      is_pre_order: false,
      is_published: true,
    },
    {
      id: 12,
      title: "Lập Trình JavaScript Nâng Cao",
      slug: "javascript-nang-cao",
      description:
        "Hiểu sâu hơn về cách Javascript hoạt động, tìm hiểu về IIFE, closure, reference types, this keyword, bind, call, apply, prototype, ...",
      image: "courses/12.png",
      icon: "courses/12/6200af2620118.png",
      video_type: "youtube",
      video: "MGhw6XliFgo",
      old_price: 0,
      price: 0,
      pre_order_price: 0,
      students_count: 22726,
      is_pro: false,
      is_selling: false,
      published_at: "2020-02-10T14:23:13.000000Z",
      is_registered: true,
      user_progress: 100,
      last_completed_at: "2022-03-10 14:33:49",
      image_url: "https://files.fullstack.edu.vn/f8-prod/courses/12.png",
      icon_url:
        "https://files.fullstack.edu.vn/f8-prod/courses/12/6200af2620118.png",
      video_url: "https://www.youtube.com/watch?v=MGhw6XliFgo",
      is_coming_soon: false,
      is_pre_order: false,
      is_published: true,
    },
    {
      id: 7,
      title: "Kiến Thức Nhập Môn IT",
      slug: "lessons-for-newbie",
      description:
        "Để có cái nhìn tổng quan về ngành IT - Lập trình web các bạn nên xem các videos tại khóa này trước nhé.",
      image: "courses/7.png",
      icon: "courses/7/6200b81f52d83.png",
      video_type: "youtube",
      video: "M62l1xA5Eu8",
      old_price: 0,
      price: 0,
      pre_order_price: 0,
      students_count: 73781,
      is_pro: false,
      is_selling: false,
      published_at: "2020-02-10T14:23:13.000000Z",
      is_registered: true,
      user_progress: 66,
      last_completed_at: "2022-01-24 14:49:26",
      image_url: "https://files.fullstack.edu.vn/f8-prod/courses/7.png",
      icon_url:
        "https://files.fullstack.edu.vn/f8-prod/courses/7/6200b81f52d83.png",
      video_url: "https://www.youtube.com/watch?v=M62l1xA5Eu8",
      is_coming_soon: false,
      is_pre_order: false,
      is_published: true,
    },
    {
      id: 6,
      title: "Node & ExpressJS",
      slug: "nodejs",
      description:
        "Học Back-end với Node & ExpressJS framework, hiểu các khái niệm khi làm Back-end và xây dựng RESTful API cho trang web.",
      image: "courses/6.png",
      icon: "courses/6/6200afb926038.png",
      video_type: "youtube",
      video: "z2f7RHgvddc",
      old_price: 0,
      price: 0,
      pre_order_price: 0,
      students_count: 27489,
      is_pro: false,
      is_selling: false,
      published_at: "2020-02-10T14:23:13.000000Z",
      is_registered: true,
      user_progress: 11,
      last_completed_at: "2022-01-08 22:24:04",
      image_url: "https://files.fullstack.edu.vn/f8-prod/courses/6.png",
      icon_url:
        "https://files.fullstack.edu.vn/f8-prod/courses/6/6200afb926038.png",
      video_url: "https://www.youtube.com/watch?v=z2f7RHgvddc",
      is_coming_soon: false,
      is_pre_order: false,
      is_published: true,
    },
    {
      id: 3,
      title: "Responsive Với Grid System",
      slug: "responsive-web-design",
      description:
        "Trong khóa này chúng ta sẽ học về cách xây dựng giao diện web responsive với Grid System, tương tự Bootstrap 4.",
      image: "courses/3.png",
      icon: "courses/3/6200afe1240bb.png",
      video_type: "youtube",
      video: "uz5LIP85J5Y",
      old_price: 0,
      price: 0,
      pre_order_price: 0,
      students_count: 32143,
      is_pro: false,
      is_selling: false,
      published_at: "2020-02-10T14:23:13.000000Z",
      is_registered: true,
      user_progress: 100,
      last_completed_at: "2021-12-26 08:47:58",
      image_url: "https://files.fullstack.edu.vn/f8-prod/courses/3.png",
      icon_url:
        "https://files.fullstack.edu.vn/f8-prod/courses/3/6200afe1240bb.png",
      video_url: "https://www.youtube.com/watch?v=uz5LIP85J5Y",
      is_coming_soon: false,
      is_pre_order: false,
      is_published: true,
    },
    {
      id: 2,
      title: "HTML, CSS từ Zero đến Hero",
      slug: "html-css",
      description:
        "Trong khóa này chúng ta sẽ cùng nhau xây dựng giao diện 2 trang web là The Band & Shopee.",
      image: "courses/2.png",
      icon: "courses/2/6200aecea81de.png",
      video_type: "youtube",
      video: "R6plN3FvzFY",
      old_price: 0,
      price: 0,
      pre_order_price: 0,
      students_count: 264399,
      is_pro: false,
      is_selling: false,
      published_at: "2020-02-10T14:23:13.000000Z",
      is_registered: true,
      user_progress: 99,
      last_completed_at: "2021-12-14 21:28:05",
      image_url: "https://files.fullstack.edu.vn/f8-prod/courses/2.png",
      icon_url:
        "https://files.fullstack.edu.vn/f8-prod/courses/2/6200aecea81de.png",
      video_url: "https://www.youtube.com/watch?v=R6plN3FvzFY",
      is_coming_soon: false,
      is_pre_order: false,
      is_published: true,
    },
  ],
};
const BlogData = [
  {
    id: 65,
    user_id: 1,
    title: "Tổng hợp các sản phẩm của học viên tại F8 👏👏",
    slug: "tong-hop-cac-san-pham-cua-hoc-vien-tai-f8",
    description: null,
    meta_title: "Tổng hợp các sản phẩm của học viên tại F8",
    meta_description:
      "Bài viết này nhằm tổng hợp lại các dự án mà học viên F8 đã hoàn thành và chia sẻ trên nhóm Học lập trình web F8. Các dự án dưới...",
    image: "blog_posts/65/6139fe28a9844.png",
    thumbnail: "blog_posts/65/6139fe28a9844.png",
    min_read: 6,
    published_at: "2021-09-09 17:46:12",
    is_approved: true,
    created_at: "2021-09-09T02:35:13.000000Z",
    reactions_count: 633,
    image_url:
      "https://files.fullstack.edu.vn/f8-prod/blog_posts/65/6139fe28a9844.png",
    thumbnail_url:
      "https://files.fullstack.edu.vn/f8-prod/blog_posts/65/6139fe28a9844.png",
    is_bookmark: false,
    is_published: true,
    user: {
      id: 1,
      username: "son-dang",
      first_name: "Sơn",
      last_name: "Đặng",
      full_name: "Sơn Đặng",
      avatar: "user_avatars/1/623d4b2d95cec.png",
      avatar_url:
        "https://files.fullstack.edu.vn/f8-prod/user_avatars/1/623d4b2d95cec.png",
      is_comment_blocked: false,
      is_blocked: false,
    },
  },
  {
    id: 279,
    user_id: 1,
    title: "[Phần 1] Tạo dự án ReactJS với Webpack và Babel",
    slug: "phan-1-tao-du-an-reactjs-voi-webpack-va-babel",
    description: null,
    meta_title: "[Phần 1] Tạo dự án ReactJS với Webpack và Babel",
    meta_description:
      "Tự tạo dự án ReactJS với webpack và babel nhằm mục đích giúp chúng ta hiểu rõ hơn về về cách create-react-app đã tạo ra dự án ReactJS như thế nào và quan...",
    image: "blog_posts/279/6153f692d366e.jpg",
    thumbnail: "blog_posts/279/6153f6932dcea.jpg",
    min_read: 12,
    published_at: "2021-09-29 12:16:03",
    is_approved: true,
    created_at: "2021-09-13T08:14:19.000000Z",
    reactions_count: 303,
    image_url:
      "https://files.fullstack.edu.vn/f8-prod/blog_posts/279/6153f692d366e.jpg",
    thumbnail_url:
      "https://files.fullstack.edu.vn/f8-prod/blog_posts/279/6153f6932dcea.jpg",
    is_bookmark: false,
    is_published: true,
    user: {
      id: 1,
      username: "son-dang",
      first_name: "Sơn",
      last_name: "Đặng",
      full_name: "Sơn Đặng",
      avatar: "user_avatars/1/623d4b2d95cec.png",
      avatar_url:
        "https://files.fullstack.edu.vn/f8-prod/user_avatars/1/623d4b2d95cec.png",
      is_comment_blocked: false,
      is_blocked: false,
    },
  },
  {
    id: 51,
    user_id: 56767,
    title: "Ký sự ngày thứ 25 học ở F8 ",
    slug: "ky-su-ngay-thu-25-hoc-o-f8-1",
    description: null,
    meta_title: "Ký sự ngày thứ 25 học ở F8 ",
    meta_description:
      "Hí ae, tôi cũng tên Sơn nhưng mà là newbie còn ông Sơn kia thì trùm rồi :))). Tôi cũng vừa mới đến với lập trình,tôi là sv năm 1....",
    image: "blog_posts/51/6139c6453456e.png",
    thumbnail: "blog_posts/51/6139c645e1a84.png",
    min_read: 1,
    published_at: "2021-09-09 15:31:02",
    is_approved: true,
    created_at: "2021-09-09T01:06:41.000000Z",
    reactions_count: 242,
    image_url:
      "https://files.fullstack.edu.vn/f8-prod/blog_posts/51/6139c6453456e.png",
    thumbnail_url:
      "https://files.fullstack.edu.vn/f8-prod/blog_posts/51/6139c645e1a84.png",
    is_bookmark: false,
    is_published: true,
    user: {
      id: 56767,
      username: "son-son-16",
      first_name: "Sơn",
      last_name: "Sơn",
      full_name: "Sơn Sơn",
      avatar:
        "https://graph.facebook.com/1642531882604203/picture?width=400&height=400",
      avatar_url:
        "https://graph.facebook.com/1642531882604203/picture?width=400&height=400",
      is_comment_blocked: false,
      is_blocked: false,
    },
  },
  {
    id: 107,
    user_id: 8,
    title: "Các nguồn tài nguyên hữu ích cho 1 front-end developer",
    slug: "cac-nguon-tai-nguyen-huu-ich-cho-1-front-end-developer",
    description: null,
    meta_title: "Các nguồn tài nguyên hữu ích cho 1 front-end developer",
    meta_description: null,
    image: "blog_posts/107/613a1f3685814.png",
    thumbnail: "blog_posts/107/613a1f36eed00.png",
    min_read: 2,
    published_at: "2021-09-09 21:50:31",
    is_approved: true,
    created_at: "2021-09-09T06:57:39.000000Z",
    reactions_count: 219,
    image_url:
      "https://files.fullstack.edu.vn/f8-prod/blog_posts/107/613a1f3685814.png",
    thumbnail_url:
      "https://files.fullstack.edu.vn/f8-prod/blog_posts/107/613a1f36eed00.png",
    is_bookmark: false,
    is_published: true,
    user: {
      id: 8,
      username: "duong-vuong",
      first_name: "Vương",
      last_name: "Dương",
      full_name: "Vương Dương",
      avatar:
        "https://graph.facebook.com/547825429409669/picture?width=400&height=400",
      avatar_url:
        "https://graph.facebook.com/547825429409669/picture?width=400&height=400",
      is_comment_blocked: false,
      is_blocked: false,
    },
  },
  {
    id: 1671,
    user_id: 9143,
    title: "Thời gian và Động lực",
    slug: "thoi-gian-va-dong-luc",
    description: null,
    meta_title: "Thời gian và Động lực",
    meta_description:
      'Có lẽ cũng rất lâu rồi mà tôi chưa đụng đến thứ được gọi là "timetable". Hay dân dã hơn thì người ta hay gọi là "Lịch thường nhật",...',
    image: "blog_posts/1671/61b6368983c16.jpg",
    thumbnail: "blog_posts/1671/61b6368a3a089.jpg",
    min_read: 6,
    published_at: "2021-12-13 05:00:00",
    is_approved: true,
    created_at: "2021-12-12T10:18:10.000000Z",
    reactions_count: 207,
    image_url:
      "https://files.fullstack.edu.vn/f8-prod/blog_posts/1671/61b6368983c16.jpg",
    thumbnail_url:
      "https://files.fullstack.edu.vn/f8-prod/blog_posts/1671/61b6368a3a089.jpg",
    is_bookmark: false,
    is_published: true,
    user: {
      id: 9143,
      username: "dong-ngo",
      first_name: "Dong",
      last_name: "Ngo",
      full_name: "Dong Ngo",
      avatar: "user_avatars/9143/616309bb2f85f.png",
      avatar_url:
        "https://files.fullstack.edu.vn/f8-prod/user_avatars/9143/616309bb2f85f.png",
      is_comment_blocked: false,
      is_blocked: false,
    },
  },
  {
    id: 677,
    user_id: 18159,
    title: "Cách đưa code lên GitHub và tạo GitHub Pages",
    slug: "cach-dua-code-len-github-va-tao-github-pages",
    description: null,
    meta_title: "Cách đưa code lên GitHub và tạo GitHub Pages",
    meta_description:
      "Ở bài viết này, mình sẽ hướng dẫn cách để đưa code lên trên Github và tạo Github Pages để xem được trang web mà các bạn đưa lên  như thế nào.",
    image: "blog_posts/677/615436b218d0a.png",
    thumbnail: "blog_posts/677/615436b284513.png",
    min_read: 4,
    published_at: "2021-09-29 16:49:38",
    is_approved: true,
    created_at: "2021-09-29T01:20:27.000000Z",
    reactions_count: 193,
    image_url:
      "https://files.fullstack.edu.vn/f8-prod/blog_posts/677/615436b218d0a.png",
    thumbnail_url:
      "https://files.fullstack.edu.vn/f8-prod/blog_posts/677/615436b284513.png",
    is_bookmark: false,
    is_published: true,
    user: {
      id: 18159,
      username: "vo-minh-kha",
      first_name: "Võ Minh",
      last_name: "Kha",
      full_name: "Võ Minh Kha",
      avatar: "user_avatars/18159/61643a2b36731.jpg",
      avatar_url:
        "https://files.fullstack.edu.vn/f8-prod/user_avatars/18159/61643a2b36731.jpg",
      is_comment_blocked: false,
      is_blocked: false,
    },
  },
  {
    id: 273,
    user_id: 74901,
    title: "Tổng hợp tài liệu tự học tiếng anh cơ bản.",
    slug: "tong-hop-tai-lieu-tu-hoc-tieng-anh-co-ban",
    description: null,
    meta_title: "Tổng hợp tài liệu tự học tiếng anh cơ bản.",
    meta_description:
      "Tài liệu tự học tiếng anh full không che. Bạn cần đọc 7749 lần các kiến thức sẽ thấm nhuần vào não bạn.",
    image: "blog_posts/273/614043e523ad9.png",
    thumbnail: "blog_posts/273/614043e58f413.png",
    min_read: 7,
    published_at: "2021-09-15 08:30:00",
    is_approved: true,
    created_at: "2021-09-13T05:09:09.000000Z",
    reactions_count: 111,
    image_url:
      "https://files.fullstack.edu.vn/f8-prod/blog_posts/273/614043e523ad9.png",
    thumbnail_url:
      "https://files.fullstack.edu.vn/f8-prod/blog_posts/273/614043e58f413.png",
    is_bookmark: false,
    is_published: true,
    user: {
      id: 74901,
      username: "le-thanh-trung-5",
      first_name: "Lê Thành",
      last_name: "Trung",
      full_name: "Lê Thành Trung",
      avatar: "user_avatars/74901/6172af710d6d3.jpg",
      avatar_url:
        "https://files.fullstack.edu.vn/f8-prod/user_avatars/74901/6172af710d6d3.jpg",
      is_comment_blocked: false,
      is_blocked: false,
    },
  },
  {
    id: 791,
    user_id: 64652,
    title: "Học như thế nào là phù hợp ?",
    slug: "hoc-nhu-the-nao-la-phu-hop",
    description: null,
    meta_title: "Học như thế nào là phù hợp ?",
    meta_description:
      "Mình xin chia sẽ cách học hiệu qua của mình khi học ở F8 một thời gian !",
    image: "blog_posts/791/615de64de7e8f.jpg",
    thumbnail: "blog_posts/791/615de64e3f449.jpg",
    min_read: 4,
    published_at: "2021-10-07 01:09:18",
    is_approved: true,
    created_at: "2021-10-06T08:04:38.000000Z",
    reactions_count: 102,
    image_url:
      "https://files.fullstack.edu.vn/f8-prod/blog_posts/791/615de64de7e8f.jpg",
    thumbnail_url:
      "https://files.fullstack.edu.vn/f8-prod/blog_posts/791/615de64e3f449.jpg",
    is_bookmark: false,
    is_published: true,
    user: {
      id: 64652,
      username: "tien-pham-ngoc",
      first_name: "Tien Pham",
      last_name: "Ngoc",
      full_name: "Tien Pham Ngoc",
      avatar:
        "https://avatar-redirect.appspot.com/google/110021593610685676732?size=400",
      avatar_url:
        "https://avatar-redirect.appspot.com/google/110021593610685676732?size=400",
      is_comment_blocked: false,
      is_blocked: false,
    },
  },
];
const VideoData = [
  {
    id: 696,
    title: '"Code Thiếu Nhi Battle" Tranh Giành Trà Sữa Size L',
    slug: "code-thieu-nhi-battle-tranh-gianh-tra-sua-size-l",
    image: "https://i.ytimg.com/vi/sgq7BH6WxL8/maxresdefault.jpg",
    video: "sgq7BH6WxL8",
    duration: 1510,
    yt_view_count: 236157,
    yt_comment_count: 180,
    yt_like_count: 5115,
    image_url: "https://i.ytimg.com/vi/sgq7BH6WxL8/maxresdefault.jpg",
    video_url: null,
  },
  {
    id: 760,
    title: "Sinh viên IT đi thực tập tại doanh nghiệp cần biết những gì?",
    slug: "sinh-vien-it-di-thuc-tap-tai-doanh-nghiep-can-biet-nhung-gi",
    image: "https://i.ytimg.com/vi/YH-E4Y3EaT4/maxresdefault.jpg",
    video: "YH-E4Y3EaT4",
    duration: 2091,
    yt_view_count: 185252,
    yt_comment_count: 227,
    yt_like_count: 4934,
    image_url: "https://i.ytimg.com/vi/YH-E4Y3EaT4/maxresdefault.jpg",
    video_url: null,
  },
  {
    id: 456,
    title: "Phương pháp học lập trình của Admin F8?",
    slug: "phuong-phap-hoc-lap-trinh-cua-admin-f8",
    image: "https://i.ytimg.com/vi/DpvYHLUiZpc/maxresdefault.jpg",
    video: "DpvYHLUiZpc",
    duration: 1446,
    yt_view_count: 66377,
    yt_comment_count: 259,
    yt_like_count: 3803,
    image_url: "https://i.ytimg.com/vi/DpvYHLUiZpc/maxresdefault.jpg",
    video_url: null,
  },
  {
    id: 533,
    title: "Làm sao để có thu nhập cao và đi xa hơn trong ngành IT?",
    slug: "lam-sao-de-co-thu-nhap-cao-va-di-xa-hon-trong-nganh-it",
    image: "https://i.ytimg.com/vi/oF7isq9IjZM/maxresdefault.jpg",
    video: "oF7isq9IjZM",
    duration: 1540,
    yt_view_count: 53189,
    yt_comment_count: 214,
    yt_like_count: 2549,
    image_url: "https://i.ytimg.com/vi/oF7isq9IjZM/maxresdefault.jpg",
    video_url: null,
  },
  {
    id: 44,
    title: "Làm được gì sau khóa học?",
    slug: "lam-duoc-gi-sau-khoa-hoc",
    image: "https://i.ytimg.com/vi/R6plN3FvzFY/maxresdefault.jpg",
    video: "R6plN3FvzFY",
    duration: 195,
    yt_view_count: 340859,
    yt_comment_count: 101,
    yt_like_count: 2323,
    image_url: "https://i.ytimg.com/vi/R6plN3FvzFY/maxresdefault.jpg",
    video_url: null,
  },
  {
    id: 690,
    title: "ReactJS là gì? Tại sao nên học ReactJS?",
    slug: "reactjs-la-gi-tai-sao-nen-hoc-reactjs",
    image: "https://i.ytimg.com/vi/x0fSBAgBrOQ/maxresdefault.jpg",
    video: "x0fSBAgBrOQ",
    duration: 641,
    yt_view_count: 95849,
    yt_comment_count: 334,
    yt_like_count: 2120,
    image_url: "https://i.ytimg.com/vi/x0fSBAgBrOQ/maxresdefault.jpg",
    video_url: null,
  },
  {
    id: 692,
    title:
      "Javascript có thể làm được gì? Giới thiệu qua về trang F8 | Học lập trình Javascript cơ bản",
    slug: "javascript-co-the-lam-duoc-gi-gioi-thieu-qua-ve-trang-f8-hoc-lap-trinh-javasc",
    image: "https://i.ytimg.com/vi/0SJE9dYdpps/maxresdefault.jpg",
    video: "0SJE9dYdpps",
    duration: 473,
    yt_view_count: 316026,
    yt_comment_count: 95,
    yt_like_count: 1974,
    image_url: "https://i.ytimg.com/vi/0SJE9dYdpps/maxresdefault.jpg",
    video_url: null,
  },
  {
    id: 691,
    title:
      "Lần trở lại này F8 sẽ làm gì cho các bạn? Học lập trình để đi làm tại F8 nào!",
    slug: "lan-tro-lai-nay-f8-se-lam-gi-cho-cac-ban-hoc-lap-trinh-de-di-lam-tai-f8-nao",
    image: "https://i.ytimg.com/vi/ZGmpvhqYSDU/maxresdefault.jpg",
    video: "ZGmpvhqYSDU",
    duration: 396,
    yt_view_count: 17679,
    yt_comment_count: 404,
    yt_like_count: 1968,
    image_url: "https://i.ytimg.com/vi/ZGmpvhqYSDU/maxresdefault.jpg",
    video_url: null,
  },
];
export { SliderData, CoursesData, BlogData, VideoData };
